version: '2'

services:

  samba:
    build: .
    environment:
      - DOMAIN=LAB
      - REALM=LAB.SAMPLE.COM
    ports:
      - "22:22"
      - "53:53"
      - "389:389"
      - "88:88"
      - "135:135"
      - "139:139"
      - "138:138"
      - "445:445"
      - "464:464"
      - "3268:3268"
      - "3269:3269"
